portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stocksapp.urls')),
]

stocksapp/urls.py
from django.urls import path, include
from . import views


app_name = 'stocksapp'
urlpatterns = [
	path('', views.charts, name='charts'),
	path('login/', views.login, name='login'),
	path('signup/', views.signup, name='signup'),
	path('logout/', views.logOut, name='logOut'),
	# path('test/', views.test, name='test'),
]

stocksapp/models.py
from django.db import models
from django.utils.crypto import get_random_string
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Account(models.Model):

	# user = models.OneToOneField(User, on_delete=models.CASCADE)

	def generate_account_num():
		not_unique = True
		while not_unique:
			unique_num = get_random_string(8, allowed_chars='0123456789')
			if not Account.objects.filter(id=unique_num):
				not_unique = False
		return str(unique_num)

	id = models.CharField(max_length=8, blank=True, editable=False, unique=True, primary_key=True, default=generate_account_num)
	username = models.CharField(max_length=20, unique=True)
	password = models.CharField(max_length=20)
	firstName = models.CharField(max_length=20)
	lastName = models.CharField(max_length=20)
	cashBalance = models.FloatField(default=50000.0)
	overallValue = models.FloatField(default=0.0)

	def __str__(self):
		return self.id


class Transaction(models.Model):
	timeDate = models.DateTimeField()
	symbol = models.CharField(max_length=10)
	shares = models.FloatField()
	buyOrSell = models.CharField(max_length=1, choices=[('B','Buy'), ('S','Sell')])
	cashPrice = models.FloatField()
	account = models.ForeignKey(Account, on_delete=models.CASCADE)

class Positions(models.Model):
	symbol = models.CharField(max_length=10)
	shares = models.FloatField()
	avgPricePerShare = models.FloatField()
	currentValue = models.FloatField(default=0.0)
	account = models.ForeignKey(Account, on_delete=models.CASCADE)

# @receiver(post_save, sender=User)
# def create_user_account(sender, instance, created, **kwargs):
#     if created:
#         Account.objects.create(user=instance)

# @receiver(post_save, sender=User)
# def save_user_accouprofile(sender, instance, **kwargs):
#     instance.profile.save()

stocksapp/forms.py
from django import forms
from .models import Account

class AccountForm(forms.ModelForm):
	class Meta:
		model = Account
		fields = ['username', 'password', 'firstName', 'lastName']
		widgets = {
      'password': forms.PasswordInput(),
    }		
	
	def __init__(self, *args, **kwargs):
		super(AccountForm, self).__init__(*args, **kwargs)
		for visible in self.visible_fields():
			visible.field.widget.attrs['class'] = 'form-control'

stocksapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib import messages
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.urls import reverse
import yfinance as yf
import plotly.graph_objects as go
import plotly.express as px
import pandas as pd
from datetime import timedelta
import random
from .models import Account, Positions, Transaction
from .forms import AccountForm
from .utils import get_or_none

now = timezone.now()

def charts(request):
	
	def newTicker(search=request.session['meta_data'] if 'meta_data' in request.session else 'GME', start=now.date() - timedelta(days = 575), end=now.date()):
		search = search.upper()
		tickerInfo = yf.Ticker(search).info
		try: 
			currPrice = tickerInfo['currentPrice']
			percentChange = round((currPrice - tickerInfo['previousClose']) / tickerInfo['previousClose'] * 100, 2)
			request.session['meta_data'] = search
		except KeyError as e:
			currPrice = 0.00
			percentChange = 0.00
			search = 'Invalid Ticker'
			messages.error(request, f"Enter a valid ticker.")


		
		if 'user' in request.session:
			a = get_or_none(Account, id=request.session['user'][2])
			if (q1 := get_or_none(Positions, account_id=request.session['user'][2], symbol=search)):
				p, avp = q1.shares, q1.avgPricePerShare 
			else: p, avp, th = 0, 0, [('N/A', now.date(), -0.1, 0.01)]
			th = [(row.symbol, row.timeDate.date(), row.shares, row.cashPrice) for row in qth] if (qth := Transaction.objects.filter(account=a).order_by('-timeDate').all()[:5]) else [('N/A', now.date(), -0.1, 0.01)]
			sharesGraph = [ ( row.symbol, row.shares, '{:,.2f}'.format(row.avgPricePerShare), ) for row in q] if (q := Positions.objects.filter(account_id=request.session['user'][2]).all()) else 'No Shares Available'
			# if sharesGraph != 'No Shares Available':
			# 	sharesGraph
			ab = a.cashBalance
		else: 
			p, avp, ab, th, sharesGraph = 0, 0, 0, [('N/A', now.date(), -0.1, 0.01)], 'No Shares Available'

		if request.POST.get('dayBttn'):
			tickerDF = yf.download(search, start=start, end=end, progress=False, interval='5m')
			layout = go.Layout(paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgb(240,242,245)', font_family= 'verdana', xaxis_rangeslider_visible=False, title_text='Day', title_x=0.5)
		elif request.POST.get('weekBttn'): 
			tickerDF = yf.download(search, start=start, end=end, progress=False, interval='30m')
			layout = go.Layout(paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgb(240,242,245)', font_family= 'verdana', xaxis_rangeslider_visible=False, title_text='Week', title_x=0.5)
		elif request.POST.get('monthBttn'): 
			tickerDF = yf.download(search, start=start, end=end, progress=False, interval='90m')
			layout = go.Layout(paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgb(240,242,245)', font_family= 'verdana', xaxis_rangeslider_visible=False, title_text='Month', title_x=0.5)
		else: 
			layout = go.Layout(paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgb(240,242,245)', font_family= 'verdana', xaxis_rangeslider_visible=False, title_text='Year', title_x=0.5)
			tickerDF = yf.download(search, start=start, end=end, progress=False)

			
		fig = go.Figure(data=[go.Candlestick(x=tickerDF.index, open=tickerDF.Open, high=tickerDF.High, low=tickerDF.Low, close=tickerDF.Close)], layout=layout)
		if request.POST.get('dayBttn') or request.POST.get('weekBttn'):
			fig.update_xaxes(rangebreaks=[dict(bounds=["sat", "mon"]), dict(bounds=[16, 9.5], pattern="hour")])
		elif request.POST.get('monthBttn'):
			fig.update_xaxes(rangebreaks=[dict(bounds=["sat", "mon"]),  dict(bounds=[14, 9.5], pattern="hour")])
		else:
			fig.update_xaxes(rangebreaks=[dict(bounds=["sat", "mon"])])

		graph = fig.to_html(full_html=False, default_height=600, default_width='100%')

		context = {'graph': graph, 'tickerName': search, 'currentPrice': currPrice, 'percentChange': percentChange, 'sharesOwned': p, 'currCashValue': '${:,.2f}'.format(p*currPrice), 'cashBalance': '{:,.2f}'.format(ab), 'sharesGraph': sharesGraph, 'avgPrice': '${:,.2f}'.format(avp), 'transHist': th}

		return render(request, 'stocksapp/home.html', context)

	if request.method == 'POST':
		endDate = now.date()
		searchedTicker = request.session.get('meta_data')
		if request.POST.get('tickerSearch'):
			request.session['meta_data'] = request.POST.get('tickerSearch', None)
			return newTicker(request.POST.get('tickerSearch', None))
		elif request.POST.get('monthBttn'):
			return newTicker(searchedTicker, endDate - timedelta(days = 30), endDate)
		elif request.POST.get('weekBttn'):
			return newTicker(searchedTicker,  endDate - timedelta(days = 7), endDate)
		elif request.POST.get('dayBttn'):
			startDate = endDate - timedelta(days = 1)
			if endDate.isoweekday() == 7:
				startDate = endDate - timedelta(days = 2)
			elif endDate.isoweekday() == 1:
				startDate = endDate - timedelta(days = 3)
			print(startDate, endDate)
			return newTicker(searchedTicker, startDate, endDate)
		elif request.POST.get('sharesToBuy') or request.POST.get('sharesToSell'):
			return buySellBot(request, searchedTicker)

	return newTicker()
	

def signup(request):
		if 'user' in request.session:
			return HttpResponseRedirect(reverse('stocksapp:charts'))

		if request.method == 'POST':
			try:
				form = AccountForm(request.POST or None)
				if form.is_valid():
						form.save()
						request.session['cashBalance'] = '50,000.00'
						request.session['user'] = [form.cleaned_data.get('username'), form.cleaned_data.get('firstName').title(), Account.objects.get(username=form.cleaned_data.get('username')).id]
						return HttpResponseRedirect(reverse('stocksapp:charts'))
			except:
					form = AccountForm()
					return render(request, 'stocksapp/signup.html', {'form': form, 'msg': 'Username is not unique, try again!'})
		else:
				form = AccountForm()
		return render(request, 'stocksapp/signup.html', {'form': form})

def login(request):
	if 'user' in request.session:
		return HttpResponseRedirect(reverse('stocksapp:charts'))

	if request.method == 'POST':
		username = request.POST['username']
		try:
			u = Account.objects.get(username=username)
			if u.password == request.POST['password']:
				request.session['user'] = [username, u.firstName.title(), u.id]
				request.session['cashBalance'] = '{:,.2f}'.format(u.cashBalance)
				return HttpResponseRedirect(reverse('stocksapp:charts'))
		except (KeyError, Account.DoesNotExist):
			return render(request, 'stocksapp/login.html', {'msg': 'Username/password incorrect, try again.'})
	else:
		return render(request, 'stocksapp/login.html')

def logOut(request):
		try:
				logout(request)
		except KeyError:
				pass
		return HttpResponseRedirect(reverse('stocksapp:charts'))

def buySellBot(request, search):

	if 'user' in request.session:
		acct = request.session['user'][2]
		a = Account.objects.get(id=acct)
		currPrice = float(yf.Ticker(search).info['currentPrice'])

		if request.POST.get('sharesToBuy'):
			stb = float(request.POST.get('sharesToBuy'))
			try:

				if stb == 0.0:
					raise ValueError(f"Must buy more than 0 shares.")
				if a.cashBalance < currPrice * stb :
					raise ValueError(f"Attempt to buy more {search} than cash available, ${round(a.cashBalance, 2)}.")

				p,t = Positions.objects.get_or_create(
					account_id=acct,
					symbol = search,
					defaults={'avgPricePerShare': currPrice, 'shares': stb}
				)

				if not t:
					p.avgPricePerShare = (p.avgPricePerShare + currPrice) / 2
					p.shares = p.shares + stb
					p.save()
				print(p)
				a.cashBalance = a.cashBalance - (currPrice * stb)
				a.save()
				tb = Transaction.objects.create(account_id=acct, timeDate=now, symbol=search, shares=stb, buyOrSell='B', cashPrice=round(-currPrice * stb, 2))
				request.session['cashBalance'] = '{:,.2f}'.format(a.cashBalance)
				print(request.session['cashBalance'])
			except ValueError as e:
				messages.error(request, e)
				return redirect('stocksapp:charts')
			messages.success(request, f"Bought {request.POST.get('sharesToBuy')} shares of {search} for {round(currPrice * stb, 2)}!" )
			return redirect('stocksapp:charts')


		elif request.POST.get('sharesToSell'):
			sts = float(request.POST.get('sharesToSell'))
			try:
				p = Positions.objects.get(account_id=acct, symbol=search)
				if sts == 0.0:
					raise ValueError(request, f"Must sell more than 0 shares.")
				if p.shares < sts:
					raise ValueError(request, f"Attempt to sell more {search} than owned, {p.shares} shares.")

				elif p.shares == sts:
					a.cashBalance = a.cashBalance + (currPrice * sts)
					a.save()
					p.delete()
					messages.success(request, f"{request.POST.get('sharesToSell')} shares of {search} sold for ${round(currPrice * sts, 2)}. 0 shares left.")
					return redirect('stocksapp:charts')

				p.shares = p.shares - sts
				a.cashBalance = a.cashBalance + (currPrice * sts)
				p.save()
				a.save()

				tb = Transaction.objects.create(account_id=acct, timeDate=now, symbol=search, shares=-sts, buyOrSell='S', cashPrice=round(currPrice * sts, 2))
				request.session['cashBalance'] = '{:,.2f}'.format(a.cashBalance)
			except Positions.DoesNotExist:
				messages.error(request, f"No shares of {search} exist to sell.")
				return redirect('stocksapp:charts')
			except ValueError as e:
				messages.error(request, e)
				return redirect('stocksapp:charts')
			messages.success(request, f"Sold {request.POST.get('sharesToSell')} shares of {search} for ${tb.cashPrice}!" )
			return redirect('stocksapp:charts')


	else:
		messages.error(request, "Please login to Buy or Sell.")
		return redirect('stocksapp:charts')



	# return render(request, 'stocksapp/charts.html', context = {'currentPrice': currPrice})

stocksapp/templates/includes/footer.html
<footer class="bg-white rounded shadow p-4 mb-4 mt-4">
    <div class="row pt-2">
        <div class="col-12 col-md-4 col-xl-6 mb-4 mb-md-0 ">
            <p class="mb-0 text-center text-lg-start">
                Stock Trading Simulator
            </p>
        </div>
        <div class="col-12 col-md-8 col-xl-6 text-center text-lg-start">
            <!-- List -->
            <ul class="list-inline list-group-flush list-group-borderless text-md-end mb-0">
                <li class="list-inline-item px-0 px-sm-2">
                    <p class="text-primary fw-normal" >Coded by Chase Ainsworth | Built with Django, Ajax & SQL</p>
                </li>
            </ul>
        </div>
    </div>
</footer>

stocksapp/templates/includes/messages.html
{% for message in messages %}
<!-- <div class="container-fluid p-0"> -->
  <div class="alert {{ message.tags }} alert-dismissible " role="alert" >
    <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="True">&times;</span>
    </button>
    {{ message | safe }}
  </div>
<!-- </div> -->
{% endfor %}

stocksapp/templates/includes/navigation.html
<nav class="navbar navbar-top navbar-expand navbar-dashboard navbar-dark ps-0 pe-2 pb-0">
              <div class="container-fluid px-0">
                <div class="d-flex justify-content-between w-100" id="navbarSupportedContent">
                  <div class="d-flex align-items-center">
                    <!-- Search form -->
                    <form method="POST" action="{% url 'stocksapp:charts' %}" class="navbar-search form-inline" id="navbar-search-main">
											{% csrf_token %}
											  <div class="input-group input-group-merge search-bar"></div>
                        <div class="input-group mb-3">
                          <button class="btn btn-outline-secondary" type="submit" id="button-addon1"><i class="fa fa-search"></i></button>
                          <input type="text" name="tickerSearch" class="form-control" id="topbarInputIconLeft" placeholder="Ticker Search" aria-label="Ticker Search" aria-describedby="topbar-addon">
                        </div>
                    </form>
                    <!-- / Search form -->
                  </div>
                  <!-- Navbar links -->
                  <ul class="navbar-nav align-items-center">
                    <li class="nav-item ms-lg-3">
                        <div class="media d-flex align-items-center">

                          {% if request.session.user %}
                          <div class="nav-item ">
                            <p class="mb-0 font-medium fw-bold text-gray-500 px-3">
                              Hello, <span class="mb-0 font-medium fw-bold text-gray-900">{{ request.session.user.1 }}</span>
                            </p>
                          </div>
                          <div class="nav-item">
                            <span class="mb-0 font-medium fw-bold text-gray-600 " ><svg xmlns="http://www.w3.org/2000/svg" width="8" height="8" fill="currentColor" class="bi bi-circle-fill" viewBox="0 0 16 16">
                              <circle cx="5" cy="5" r="5"/>
                            </svg></span>
                          </div>
                          <div class="nav-item ">
                            <p class="mb-0 font-medium fw-bold text-gray-500 px-3">
                              $<span class="mb-0 font-medium fw-bold text-gray-900">{{request.session.cashBalance}}</span>
                            </p>
                          </div>
                          <div class="nav-item">
                            <span class="mb-0 font-medium fw-bold text-gray-600 " ><svg xmlns="http://www.w3.org/2000/svg" width="8" height="8" fill="currentColor" class="bi bi-circle-fill" viewBox="0 0 16 16">
                              <circle cx="5" cy="5" r="5"/>
                            </svg></span>
                          </div>
                          <div class="nav-link">
                            <a class="mb-0 font-medium fw-bold text-gray-500" href="{% url 'stocksapp:logOut' %}">Logout</a>
                          </div>
                          {% else %}
                          <div class="nav-link">
                            <a class="mb-0 font-medium fw-bold text-gray-600 " href="{% url 'stocksapp:login' %}">Login</a>
                          </div>
                          <div class="nav-item">
                            <span class="mb-0 font-medium fw-bold text-gray-600 " ><svg xmlns="http://www.w3.org/2000/svg" width="8" height="8" fill="currentColor" class="bi bi-circle-fill" viewBox="0 0 16 16">
                              <circle cx="5" cy="5" r="5"/>
                            </svg></span>
                          </div>
                          <div class="nav-link">
                            <a class="mb-0 font-medium fw-bold text-gray-600" href="{% url 'stocksapp:signup' %}">Signup</a>
                          </div>
                          {% endif %}
                        </div>
                      

                    </li>
                    <li>
                      
                    </li>
                  </ul>
                </div>
              </div>
            </nav>

stocksapp/templates/includes/scripts.html
<!-- Core -->
<script type="application/javascript" src="/static/app_assets/jquery/js/jquery-3.3.1.min.js"></script>
<script type="application/javascript" src="/static/app_assets/jquery/js/jquery-confirm.min.js"></script>
<script type="text/javascript" src="/static/app_assets/jquery/cookie/jquery.cookie.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<!-- Vendor JS -->
<script src="/static/assets/vendor/onscreen/dist/on-screen.umd.min.js"></script>

<!-- Slider -->
<script src="/static/assets/vendor/nouislider/distribute/nouislider.min.js"></script>

<!-- Smooth scroll -->
<script src="/static/assets/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js"></script>

<!-- Charts -->
<script src="/static/assets/vendor/chartist/dist/chartist.min.js"></script>
<script src="/static/assets/vendor/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js"></script>

<!-- Datepicker -->
<script src="/static/assets/vendor/vanillajs-datepicker/dist/js/datepicker.min.js"></script>

<!-- Sweet Alerts 2 -->
<script src="/static/assets/vendor/sweetalert2/dist/sweetalert2.all.min.js"></script>

<!-- Moment JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>

<!-- Vanilla JS Datepicker -->
<script src="/static/assets/vendor/vanillajs-datepicker/dist/js/datepicker.min.js"></script>

<!-- Notyf -->
<script src="/static/assets/vendor/notyf/notyf.min.js"></script>

<!-- Simplebar -->
<script src="/static/assets/vendor/simplebar/dist/simplebar.min.js"></script>

<!-- Github buttons -->
<script async defer src="https://buttons.github.io/buttons.js"></script>

<!-- Volt JS -->
<!-- <script src="/static/assets/js/volt.js"></script> -->

<!-- Custom app script -->
<script type="application/javascript" src="/static/app_assets/js/notify.js"></script>
<script type="application/javascript" src="/static/app_assets/js/app_js.js"></script>
<script>
    {% if messages %}
        {% for message in messages %}
            notification['{{ message.tags }}']("<p>" + '{{ message|capfirst }}' + "</p>");
        {% endfor %}
    {% endif %}
</script>

stocksapp/templates/includes/settings-box.html
    <div class="theme-settings card bg-gray-800 pt-2 collapse" id="theme-settings">
        <div class="card-body bg-gray-800 text-white pt-4">
            <button type="button" class="btn-close theme-settings-close" aria-label="Close" data-toggle="collapse"
                href="#theme-settings" role="button" aria-expanded="false" aria-controls="theme-settings"></button>
            <div class="d-flex justify-content-between align-items-center mb-3">
                <p class="m-0 mb-1 me-4 fs-7">Open source <span role="img" aria-label="gratitude">💛</span></p>
                <a class="github-button" href="https://github.com/app-generator/boilerplate-code-django-dashboard"
                    data-color-scheme="no-preference: dark; light: light; dark: light;" data-icon="octicon-star"
                    data-size="large" data-show-count="true"
                    aria-label="Star themesberg/volt-bootstrap-5-dashboard on GitHub">Star</a>
            </div>
            <a href="https://appseed.us/admin-dashboards/django-dashboard-volt" target="_blank"
                class="btn btn-secondary d-inline-flex align-items-center justify-content-center mb-3 w-100">
                Download 
                <svg class="icon icon-xs ms-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M2 9.5A3.5 3.5 0 005.5 13H9v2.586l-1.293-1.293a1 1 0 00-1.414 1.414l3 3a1 1 0 001.414 0l3-3a1 1 0 00-1.414-1.414L11 15.586V13h2.5a4.5 4.5 0 10-.616-8.958 4.002 4.002 0 10-7.753 1.977A3.5 3.5 0 002 9.5zm9 3.5H9V8a1 1 0 012 0v5z" clip-rule="evenodd"></path></svg>
            </a>
            <p class="fs-7 text-gray-300 text-center">MIT License | Free Support</p>
        </div>
    </div>

    <div class="card theme-settings bg-gray-800 theme-settings-expand" id="theme-settings-expand">
        <div class="card-body bg-gray-800 text-white rounded-top p-3 py-2">
            <span class="fw-bold d-inline-flex align-items-center h6">
                <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M11.49 3.17c-.38-1.56-2.6-1.56-2.98 0a1.532 1.532 0 01-2.286.948c-1.372-.836-2.942.734-2.106 2.106.54.886.061 2.042-.947 2.287-1.561.379-1.561 2.6 0 2.978a1.532 1.532 0 01.947 2.287c-.836 1.372.734 2.942 2.106 2.106a1.532 1.532 0 012.287.947c.379 1.561 2.6 1.561 2.978 0a1.533 1.533 0 012.287-.947c1.372.836 2.942-.734 2.106-2.106a1.533 1.533 0 01.947-2.287c1.561-.379 1.561-2.6 0-2.978a1.532 1.532 0 01-.947-2.287c.836-1.372-.734-2.942-2.106-2.106a1.532 1.532 0 01-2.287-.947zM10 13a3 3 0 100-6 3 3 0 000 6z" clip-rule="evenodd"></path></svg>
                Settings
            </span>
        </div>
    </div>